---
# List of all possible flags for each category of tests used in the case where
# "all" is specified.
flags:
  builds:
    - emulator
    - emulator-jb
    - emulator-kk
    - linux32_goanna  # b2g desktop linux 32 bit
    - linux64_goanna  # b2g desktop linux 64 bit
    - linux64-mulet  # Firefox desktop - b2g goanna linux 64 bit
    - macosx64_goanna # b2g desktop osx 64 bit
    - win32_goanna    # b2g desktop win 32 bit
    - flame-kk       # b2g flame kitkat
    - flame-kk-eng   # b2g flame eng build

  tests:
    - cppunit
    - crashtest
    - crashtest-ipc
    - gaia-build
    - gaia-build-unit
    - gaia-js-integration
    - gaia-linter
    - gaia-unit
    - gaia-unit-oop
    - gaia-ui-test-oop
    - gaia-ui-test-accessibility
    - gaia-ui-test-functional
    - gaia-ui-test-unit
    - jetpack
    - jittests
    - jsreftest
    - marionette
    - marionette-webapi
    - mochitest
    - mochitest-media
    - mochitest-oop
    - mozmill
    - reftest
    - reftest-ipc
    - reftest-no-accel
    - reftest-sanity-oop
    - web-platform-tests
    - xpcshell

